//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProyectoIntegrador_4B.com.somee.losmugiwara.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Base_DatosSoap", Namespace="http://tempuri.org/")]
    public partial class Base_Datos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IngresarOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngresarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarPrecioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Base_Datos() {
            this.Url = "http://www.losmugiwara.somee.com/Base_Datos.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IngresarCompletedEventHandler IngresarCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioCompletedEventHandler RegistrarUsuarioCompleted;
        
        /// <remarks/>
        public event IngresarProductoCompletedEventHandler IngresarProductoCompleted;
        
        /// <remarks/>
        public event EliminarProductoCompletedEventHandler EliminarProductoCompleted;
        
        /// <remarks/>
        public event ModificarPrecioCompletedEventHandler ModificarPrecioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ingresar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Ingresar(string usuario, string contra) {
            object[] results = this.Invoke("Ingresar", new object[] {
                        usuario,
                        contra});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IngresarAsync(string usuario, string contra) {
            this.IngresarAsync(usuario, contra, null);
        }
        
        /// <remarks/>
        public void IngresarAsync(string usuario, string contra, object userState) {
            if ((this.IngresarOperationCompleted == null)) {
                this.IngresarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresarOperationCompleted);
            }
            this.InvokeAsync("Ingresar", new object[] {
                        usuario,
                        contra}, this.IngresarOperationCompleted, userState);
        }
        
        private void OnIngresarOperationCompleted(object arg) {
            if ((this.IngresarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresarCompleted(this, new IngresarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrarUsuario(string nombreapellido, string usuario, string contraseña, int telefono, System.DateTime fechanacimiento) {
            this.Invoke("RegistrarUsuario", new object[] {
                        nombreapellido,
                        usuario,
                        contraseña,
                        telefono,
                        fechanacimiento});
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(string nombreapellido, string usuario, string contraseña, int telefono, System.DateTime fechanacimiento) {
            this.RegistrarUsuarioAsync(nombreapellido, usuario, contraseña, telefono, fechanacimiento, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(string nombreapellido, string usuario, string contraseña, int telefono, System.DateTime fechanacimiento, object userState) {
            if ((this.RegistrarUsuarioOperationCompleted == null)) {
                this.RegistrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuario", new object[] {
                        nombreapellido,
                        usuario,
                        contraseña,
                        telefono,
                        fechanacimiento}, this.RegistrarUsuarioOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IngresarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IngresarProducto(string categoria, string nombre, double precio) {
            this.Invoke("IngresarProducto", new object[] {
                        categoria,
                        nombre,
                        precio});
        }
        
        /// <remarks/>
        public void IngresarProductoAsync(string categoria, string nombre, double precio) {
            this.IngresarProductoAsync(categoria, nombre, precio, null);
        }
        
        /// <remarks/>
        public void IngresarProductoAsync(string categoria, string nombre, double precio, object userState) {
            if ((this.IngresarProductoOperationCompleted == null)) {
                this.IngresarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresarProductoOperationCompleted);
            }
            this.InvokeAsync("IngresarProducto", new object[] {
                        categoria,
                        nombre,
                        precio}, this.IngresarProductoOperationCompleted, userState);
        }
        
        private void OnIngresarProductoOperationCompleted(object arg) {
            if ((this.IngresarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarProducto(string producto) {
            this.Invoke("EliminarProducto", new object[] {
                        producto});
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(string producto) {
            this.EliminarProductoAsync(producto, null);
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(string producto, object userState) {
            if ((this.EliminarProductoOperationCompleted == null)) {
                this.EliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("EliminarProducto", new object[] {
                        producto}, this.EliminarProductoOperationCompleted, userState);
        }
        
        private void OnEliminarProductoOperationCompleted(object arg) {
            if ((this.EliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarPrecio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarPrecio(string producto, double precio) {
            this.Invoke("ModificarPrecio", new object[] {
                        producto,
                        precio});
        }
        
        /// <remarks/>
        public void ModificarPrecioAsync(string producto, double precio) {
            this.ModificarPrecioAsync(producto, precio, null);
        }
        
        /// <remarks/>
        public void ModificarPrecioAsync(string producto, double precio, object userState) {
            if ((this.ModificarPrecioOperationCompleted == null)) {
                this.ModificarPrecioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarPrecioOperationCompleted);
            }
            this.InvokeAsync("ModificarPrecio", new object[] {
                        producto,
                        precio}, this.ModificarPrecioOperationCompleted, userState);
        }
        
        private void OnModificarPrecioOperationCompleted(object arg) {
            if ((this.ModificarPrecioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarPrecioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IngresarCompletedEventHandler(object sender, IngresarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngresarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngresarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IngresarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModificarPrecioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591